apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-statefulset-role
  namespace: javamysqldemo
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
