apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-statefulset-binding
  namespace: javamysqldemo
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: javamysqldemo
roleRef:
  kind: Role
  name: jenkins-statefulset-role
  apiGroup: rbac.authorization.k8s.io